---
- name: "Automate docker build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop nginx-app1
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm nginx-app1
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi mohamedmyolba/nginx-app
    ignore_errors: yes
    
  - name: build new image 
    command: docker build -t mohamedmtolba/nginx-app .
    
  - name: push docker image 
    command: docker push mohamedmtolba/nginx-app

  - name: run new container
    command: docker run -it -d --name nginx-app1 -p 11000:80 mohamedmtolba/nginx-app
      