apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: k8sname
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: mohamedmtolba/nginx-app
        ports:
        - containerPort: 80