apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: k8sname
  labels:
    app: test-app
spec:
  selector:
  
    app: test-app
  type: NodePort
  ports:
     - port: 80      
       targetPort: 80 
  